-- MySQL Script generated by MySQL Workbench
-- 10/17/18 16:33:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



CREATE TABLE `clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `name` VARCHAR(45) NOT NULL COMMENT 'Le nom du client',
  `adresse` VARCHAR(128) NOT NULL COMMENT 'adresse de livraison',
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(60) NOT NULL
) 
ENGINE = InnoDB;

CREATE TABLE `items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(45) NOT NULL COMMENT 'Le nom du produit',
  `description` TEXT NULL COMMENT 'La description du produit',
  `picture` VARCHAR(128) NULL COMMENT 'URL de l\image du produit',
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Le tarif journalier',
  `stock` INT(11) NOT NULL DEFAULT 0 COMMENT 'Le stock du produit'
)
UPDATE `items`
SET `stock` = FLOOR(RAND() * 100) + 1;

-- ici je demande des valeurs aléatoires entre 1 et 100

ENGINE = InnoDB;


CREATE TABLE `reservations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `date_commande` DATE NOT NULL ,
  `date_retour` DATE NOT NULL ,
  `client_id` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
  FOREIGN KEY (`item_id`) REFERENCES `items`(`id`)
)
ENGINE = InnoDB;

-- Table many to many

CREATE TABLE `reservation_items` (
  `reservation_id` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`reservation_id`, `item_id`),
  FOREIGN KEY (`reservation_id`) REFERENCES `reservations`(`id`),
  FOREIGN KEY (`item_id`) REFERENCES `items`(`id`)
)
ENGINE = InnoDB;



START TRANSACTION;
INSERT INTO `clients` (`id`, `name`,  `adresse`, `email`, `password`) VALUES (1, 'Philippe Candille','rue de la premiere', 'philippe@oclock.io', 'rocknroll');
INSERT INTO `clients` (`id`, `name`, `adresse`, `email`, `password`) VALUES (2, 'Lucie Copin', 'rue de la deuxieme', 'lucie@oclock.io', 'cameleon');
INSERT INTO `clients` (`id`, `name`,  `adresse`, `email`, `password`) VALUES (3, 'Nicole Café','rue de la troisieme', 'nicole@oclock.io', 'onews');

COMMIT;


START TRANSACTION;
INSERT INTO items (name, description, picture, price)
VALUES
    ('Drone DJI Mavic Air 2', 'Drone compact avec une excellente qualité d\image', 'assets/images/produits/djiMAvicAir.jpg', 19.99),

    ('Appareil Photo Sony Alpha A7III', 'Appareil photo plein format avec 24,2 megapixels', 'assets/images/produits/sonyA7III.jpg', 15.99),

    ('Caméra de Voyage GoPro Hero 9', 'Caméra d\action 4K avec écran tactile.', 'assets/images/produits/gopro.jpg', 19.99),

    ('Drone DJI Phantom 4 Pro', 'Drone professionnel avec caméra 4K.', 'assets/images/produits/djiPhantom4.jpg', 29.99),

    ('Appareil Photo Canon EOS 5D Mark IV', 'Appareil photo reflex numérique haut de gamme.', 'assets/images/produits/canonMark.jpg', 19.99),

    ('Caméra de Voyage Panasonic Lumix GX9', 'Caméra compacte avec stabilisation d\image.', 'assets/images/produits/panasonicLumix.jpg', 24.99),

    ('Drone DJI Mini 2', 'Drone ultra-léger et compact pour les débutants.', 'assets/images/produits/mini2.jpg', 19.99),

    ('Appareil Photo Olympus OM-D', 'Appareil photo 4K reflex numérique avec 30,9 mégapixels.', 'assets/images/produits/olympus.jpg', 9.99);

  COMMIT;